### ISSUE TITLE
Reporte Practica

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Band-hi#2]
[Practica TextBox AutoExplicativa.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Band-hi/files/6290944/Practica.TextBox.AutoExplicativa.pdf)

**Comment by christopheremv** [comment]
calificación 20 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
